[[constraint]]
  branch = "master"
  name = "github.com/dgraph-io/badger"

[[constraint]]
  branch = "master"
  name = "github.com/dgraph-io/dgo"

[[constraint]]
  branch = "master"
  name = "github.com/docopt/docopt-go"

[[constraint]]
  version = "1.7.1"
  name = "github.com/bitherhq/go-bither"
